name: LegoPieceFinder
options:
  bundleIdPrefix: com.legopiecefinder
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"

targets:
  LegoPieceFinder:
    type: application
    platform: iOS
    sources:
      - LegoPieceFinder
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_KEY_NSCameraUsageDescription: "LegoPieceFinder needs camera access to photograph manual pages and scan LEGO pieces."
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        SWIFT_VERSION: "6.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

  LegoPieceFinderTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - LegoPieceFinderTests
    resources:
      - path: LegoPieceFinderTests/Resources
        buildPhase: resources
    dependencies:
      - target: LegoPieceFinder
    settings:
      base:
        SWIFT_VERSION: "6.0"
        GENERATE_INFOPLIST_FILE: YES
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/LegoPieceFinder.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/LegoPieceFinder"
        CODE_SIGN_STYLE: Automatic
