name: LegoPieceFinder
options:
  bundleIdPrefix: com.legopiecefinder
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"

targets:
  LegoPieceFinder:
    type: application
    platform: iOS
    sources:
      - LegoPieceFinder
    settings:
      base:
        INFOPLIST_KEY_NSCameraUsageDescription: "LegoPieceFinder needs camera access to photograph manual pages and scan LEGO pieces."
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        SWIFT_VERSION: "6.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: YES
